language: php
php:
  - 5.4
before_script:
  - composer install --dev --no-interaction
  - php vendor/autoload.php
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml
after_script:
  - php vendor/bin/coveralls
